backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
media_library:
  name: cloudinary
  config:
    cloud_name: ddomozydd
    api_key: 185835969258919
media_folder: static/img
site_url: https://bigduckmusic.com
display_url: https://bigduckmusic.com
logo_url: https://bigduckmusic.com/static/Big-Duck_Transparent-d2aba81174570b33c2dd317f346e5bf6.svg
public_folder: /img

collections:
  - name: 'blog'
    label: 'Features'
    folder: 'src/pages/features'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'text'}
      - {label: 'Review', name: 'isReview', widget: 'boolean', default: false}
      - {label: 'Spotify link', name: 'spotify', widget: 'string'}
      - {
          label: 'Featured Post',
          name: 'featuredpost',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Featured Image',
          name: 'featuredimageo',
          widget: image,
          multiple: false,
        }
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Tags', name: 'tags', widget: 'list'}

      - {
          label: 'Socials',
          name: 'socials',
          widget: 'list',
          fields: [{label: 'url', name: 'url', widget: 'string'}],
        }

  - name: 'gigs'
    label: 'Gigs'
    folder: 'src/pages/gigs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'gig-post',
        }
      - label: 'Carousel'
        name: 'test'
        widget: 'image'
        media_library:
          config:
            multiple: true
      - label: 'poster'
        name: 'poster'
        widget: 'image'
        media_library:
          config:
            multiple: false
      - label: 'featured'
        name: 'featuredimageo'
        widget: 'image'
        media_library:
          config:
            multiple: false

      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Spotify link', name: 'spotify', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'text'}
      - {
          label: 'Featured Post',
          name: 'featuredpost',
          widget: 'boolean',
          default: false,
        }
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - {label: 'Tags', name: 'tags', widget: 'list'}

      - {
          label: 'Socials',
          name: 'socials',
          widget: 'list',
          fields: [{label: 'url', name: 'url', widget: 'string'}],
        }

  - name: 'picks'
    label: 'picks'
    folder: 'src/pages/picks'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'picks-page',
        }
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: Title, name: title, widget: string}
      - {
          label: 'Featured Images',
          name: 'featuredimages',
          widget: 'list',
          fields:
            [
              {label: 'image', name: 'image', widget: 'image'},
              {label: 'link', name: 'link', widget: 'string'},
            ],
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
